// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4zTuZtGr4qeA1QHi9mTAtU42kv2lDYSQ',
    appId: '1:778464187551:android:62110c9108a55981ad7eaa',
    messagingSenderId: '778464187551',
    projectId: 'mitch-chat-app-c756a',
    storageBucket: 'mitch-chat-app-c756a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCXBFYJXQErYvjo3jmoK5K9Jt11hf390',
    appId: '1:778464187551:ios:b26b27ff301295faad7eaa',
    messagingSenderId: '778464187551',
    projectId: 'mitch-chat-app-c756a',
    storageBucket: 'mitch-chat-app-c756a.firebasestorage.app',
    iosBundleId: 'com.fuad.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_1BsxfGFb1Xr76YVbLycRQLJKBZ942k',
    appId: '1:778464187551:web:8b1812ba4825015ead7eaa',
    messagingSenderId: '778464187551',
    projectId: 'mitch-chat-app-c756a',
    authDomain: 'mitch-chat-app-c756a.firebaseapp.com',
    storageBucket: 'mitch-chat-app-c756a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCXBFYJXQErYvjo3jmoK5K9Jt11hf390',
    appId: '1:778464187551:ios:b26b27ff301295faad7eaa',
    messagingSenderId: '778464187551',
    projectId: 'mitch-chat-app-c756a',
    storageBucket: 'mitch-chat-app-c756a.firebasestorage.app',
    iosBundleId: 'com.fuad.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa_1BsxfGFb1Xr76YVbLycRQLJKBZ942k',
    appId: '1:778464187551:web:cb6a9ab7b8983ffbad7eaa',
    messagingSenderId: '778464187551',
    projectId: 'mitch-chat-app-c756a',
    authDomain: 'mitch-chat-app-c756a.firebaseapp.com',
    storageBucket: 'mitch-chat-app-c756a.firebasestorage.app',
  );

}